package drools;

import drools.MotroInferenciaDrools.*;
 
rule "DIAGNOSTICO 1"
	when
		m : Message( resp1 ==  Message.SI && resp2 == Message.NO, myMessage : message )
	then
		m.setMessage("DIAGNOSTICO 1");
end

rule "DIAGNOSTICO 2"
	when
		m : Message( resp1 ==  Message.SI && resp2 == Message.SI, myMessage : message )
	then
		m.setMessage("DIAGNOSTICO 2");
end

rule "DIAGNOSTICO 3"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.SI 
		          && resp5 == Message.SI, myMessage : message )
	then
		m.setMessage("DIAGNOSTICO 3");
end

rule "DIAGNOSTICO 4"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.SI 
		          && resp5 == Message.NO && resp6 == Message.SI, myMessage : message )
	then
		m.setMessage("DIAGNOSTICO 4");
end

rule "DIAGNOSTICO 5"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.SI 
		          && resp5 == Message.NO && resp6 == Message.NO && resp7 == Message.SI, 
		          myMessage : message )
	then
		m.setMessage("DIAGNOSTICO 5");
end

rule "DIAGNOSTICO 6"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.SI 
				  && resp5 == Message.NO && resp6 == Message.NO && resp7 == Message.NO
				  && resp8 == Message.SI, myMessage : message )
	then
		m.setMessage("DIAGNOSTICO 6");
end

rule "DIAGNOSTICO 7"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.SI 
				  && resp5 == Message.NO && resp6 == Message.NO && resp7 == Message.NO
				  && resp8 == Message.NO, myMessage : message )
	then
		m.setMessage("DIAGNOSTICO 7");
end

rule "DIAGNOSTICO 8"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.NO, myMessage : message )
	then
		m.setMessage("DIAGNOSTICO 8");
end

rule "DIAGNOSTICO 9"
	when
		m : Message( resp1 ==  Message.NO && resp3 == Message.NO, myMessage : message )
	then
		m.setMessage("DIAGNOSTICO 9");
end