package drools;

import drools.MotroInferenciaDrools.*;
 
rule "DIAGNOSTICO 1"
	when
		m : Message( resp1 ==  Message.SI && resp2 == Message.NO, myMessage : message )
	then
		m.setMessage("Delirium debido a una enfermedad medica");
end

rule "DIAGNOSTICO 2"
	when
		m : Message( resp1 ==  Message.SI && resp2 == Message.SI, myMessage : message )
	then
		m.setMessage("Delirium debido a multiples etiologias");
end

rule "DIAGNOSTICO 3"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.SI 
		          && resp5 == Message.SI, myMessage : message )
	then
		m.setMessage("Delirium debido a multiples etiologias");
end

rule "DIAGNOSTICO 4"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.SI 
		          && resp5 == Message.NO && resp6 == Message.SI, myMessage : message )
	then
		m.setMessage("Demencia Vascular");
end

rule "DIAGNOSTICO 5"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.SI 
		          && resp5 == Message.NO && resp6 == Message.NO && resp7 == Message.SI, 
		          myMessage : message )
	then
		m.setMessage("Demencia debida a una enfermedad medica");
end

rule "DIAGNOSTICO 6"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.SI 
				  && resp5 == Message.NO && resp6 == Message.NO && resp7 == Message.NO
				  && resp8 == Message.SI, myMessage : message )
	then
		m.setMessage("Demencia tipo Alzheimer");
end

rule "DIAGNOSTICO 7"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.SI 
				  && resp5 == Message.NO && resp6 == Message.NO && resp7 == Message.NO
				  && resp8 == Message.NO, myMessage : message )
	then
		m.setMessage("Demencia no especificada");
end

rule "DIAGNOSTICO 8"
	when
		m : Message( resp1 == Message.NO && resp3 == Message.SI && resp4 == Message.NO, myMessage : message )
	then
		m.setMessage("Trastorno amnesico debido a una enfermedad medica");
end

rule "DIAGNOSTICO 9"
	when
		m : Message( resp1 ==  Message.NO && resp3 == Message.NO, myMessage : message )
	then
		m.setMessage("No presenta tratorno");
end