package com.sample
 
import com.sample.DroolsTest.Message;
 
rule "DIAGNOSTICO 1"
	when
		m : Message( resp1 ==  Message.SI && resp2 == Message.NO, myMessage : message )
	then
		System.out.println( "DIAGNOSTICO 1" );
end

rule "DIAGNOSTICO 2"
	when
		m : Message( resp1 ==  Message.SI && resp2 == Message.SI, myMessage : message )
	then
		System.out.println( "DIAGNOSTICO 2" );
end

rule "DIAGNOSTICO 3"
	when
		m : Message( resp1 ==  Message.SI && resp3 == Message.SI && resp4 == Message.SI 
		&& resp5 == Message.SI, myMessage : message )
	then
		System.out.println( "DIAGNOSTICO 3" );
end